# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "public_network", bridge: [
    "enp4s0"
  ]
  config.vm.provision "shell", path: "scripts_vagrant/prov.sh"
  config.vm.provision "shell", path: "scripts_packer/minimize.sh"
  config.vm.provision "shell" do |s|
    s.path = "scripts_packer/vagrant.sh"
    s.env = {
      :HOME_DIR => "/home/vagrant",
      :SSH_USER => "vagrant"
    }
  end
end
